// Generate src/components/icons.ts from lucide-static for the exact icons the web app uses.
const nodes = require('lucide-static/icon-nodes.json');
const fs = require('fs');

const webIcons = 'Activity AlertCircle AlertTriangle AlignLeft Archive ArrowRight BarChart2 Bell Briefcase Building Building2 Calendar Check CheckCircle CheckCircle2 CheckSquare ChevronDown ChevronLeft ChevronRight ChevronUp Circle Clock Crown Download Eye FileText Flag Folder FolderKanban FolderOpen GitFork GripVertical Hash HelpCircle Home Kanban Layers LayoutGrid ListTodo Loader2 Lock LogOut Mail Menu MessageSquare Moon MoreVertical Paperclip Pencil PieChart Play Plus RefreshCw Rocket RotateCcw Search Send Settings Shield ShieldCheck Star Sun Tag Target Trash2 TrendingDown TrendingUp User UserPlus Users X'.split(' ');

const kebab = s => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
// lucide renamed a handful of icons since the web app's lucide version
const ALIAS = {
  AlertCircle: 'circle-alert',
  AlertTriangle: 'triangle-alert',
  AlignLeft: 'text-align-start',
  BarChart2: 'chart-bar-big',
  Building2: 'building-complex',
  CheckCircle: 'circle-check',
  CheckCircle2: 'circle-check-big',
  CheckSquare: 'square-check-big',
  HelpCircle: 'circle-question-mark',
  Home: 'house',
  Loader2: 'loader-circle',
  MoreVertical: 'ellipsis-vertical',
  PieChart: 'chart-pie',
  Trash2: 'trash',
};

const out = {};
for (const name of webIcons) {
  const key = ALIAS[name] || kebab(name);
  if (!nodes[key]) { console.error('MISSING', name, '->', key); process.exit(1); }
  out[name] = nodes[key];
}

const ts = `// AUTO-GENERATED by scripts/gen-icons.js — exact Lucide icon data used by the web app.
// Each entry is a list of [tag, attrs] primitives rendered by <Icon />.
export type IconTag = 'path' | 'circle' | 'rect' | 'line' | 'polyline' | 'polygon' | 'ellipse';
export type IconNode = [IconTag, Record<string, any>];

export const ICONS: Record<string, IconNode[]> = ${JSON.stringify(out, null, 1)};
`;
fs.writeFileSync('src/components/icons.ts', ts);
console.log('Generated src/components/icons.ts with', Object.keys(out).length, 'icons');
